In [10]:
import numpy as np
D = lambda n: np.c_[-np.identity(n-1), np.zeros(n-1)]+np.c_[np.zeros(n-1), np.identity(n-1)]
D(5)

array([[-1.,  1.,  0.,  0.,  0.],
       [ 0., -1.,  1.,  0.,  0.],
       [ 0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0., -1.,  1.]])

In [11]:
D(4)

array([[-1.,  1.,  0.,  0.],
       [ 0., -1.,  1.,  0.],
       [ 0.,  0., -1.,  1.]])

In [12]:
Delta=D(4)@D(5)
print(Delta)

[[ 1. -2.  1.  0.  0.]
 [ 0.  1. -2.  1.  0.]
 [ 0.  0.  1. -2.  1.]]


In [ ]:
#population dynamics
import matplotlib.pyplot as plt
plt.ion()
D = population_data();
b = D['birth_rate'];
d = D['death_rate'];
# Dynamics matrix for populaion dynamics
A = np.vstack([b, np.column_stack([np.diag(1-d[:-1]),np.zeros((len(d)-1))])])
# Contribution factor to total poulation in 2020
# from each age in 2010
cf = np.ones(100) @ np.linalg.matrix_power(A,10) # Contribution factor 
plt.plot(cf)
plt.xlabel('Age')
plt.ylabel('Factor')

In [ ]:
#QR factorization
def QR_factorization(A):
    Q_transpose = np.array(gram_schmidt(A.T))
    R = Q_transpose @ A
    Q = Q_transpose.T
    return Q, R
Q, R = QR_factorization(A)

In [ ]:
Q,R=np.lianlg.qr(A)

In [15]:
A = np.random.normal(size = (6,4))
Q, R = np.linalg.qr(A)
R

array([[ 3.59111633, -0.50461572, -0.10323723, -3.08731055],
       [ 0.        , -2.14910081, -0.34660744, -1.31663428],
       [ 0.        ,  0.        ,  1.35906731, -0.88276247],
       [ 0.        ,  0.        ,  0.        , -1.01416784]])

In [16]:
Q.T@Q

array([[ 1.00000000e+00, -7.03757326e-18, -1.77541341e-17,
         3.43574805e-17],
       [-7.03757326e-18,  1.00000000e+00,  2.04609238e-16,
         2.43791789e-17],
       [-1.77541341e-17,  2.04609238e-16,  1.00000000e+00,
         1.05413390e-16],
       [ 3.43574805e-17,  2.43791789e-17,  1.05413390e-16,
         1.00000000e+00]])

In [17]:
#inverse
A = np.array([[1,-2,3], [0,2,2], [-4,-4, -4]])
B=np.linalg.inv(A)
B

array([[-2.77555756e-17, -5.00000000e-01, -2.50000000e-01],
       [-2.00000000e-01,  2.00000000e-01, -5.00000000e-02],
       [ 2.00000000e-01,  3.00000000e-01,  5.00000000e-02]])

In [18]:
B@A

array([[ 1.00000000e+00, -2.22044605e-16, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  8.32667268e-17],
       [ 0.00000000e+00,  5.55111512e-17,  1.00000000e+00]])

In [19]:
A@B

array([[ 1.00000000e+00,  0.00000000e+00, -1.38777878e-17],
       [ 5.55111512e-17,  1.00000000e+00,  1.38777878e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [20]:
#dual basis
A = np.array([[1,0,1], [4,-3,-4], [1,-1,-2]])
B = np.linalg.inv(A)
x = np.array([0.2,-0.3,1.2])
RHS = (B[0,:]@x)*A[:,0]+(B[1,:]@x)*A[:,1]+(B[2,:]@x)*A[:,2]
print(RHS)

[ 0.2 -0.3  1.2]


In [23]:
#inverse via QR factorization
A=np.random.normal(size=(3,3))
np.linalg.inv(A)
Q,R=np.linalg.qr(A)
np.linalg.inv(R)@Q.T#@A

array([[-1.53373053,  1.08737667,  0.93092563],
       [ 0.78610892, -0.16698672, -0.80051194],
       [ 0.26152016,  0.4161391 ,  0.45174182]])

In [ ]:
#solving linear equations
#back substitution
def back_subst(R,b_tilde):
    n=R.shape[0]
    x=np.zeros(n)
    for i in reversed(range(n)):
        

In [ ]:
#back substitution
def back_subst(R,b_tilde):
    n=R.shape[0]
    x=np.zeros(n)
    for i in range(n-1,-1):
        x[i]=b_tilde[i]
        for j in range(i+1,n):
            x[i]=x[i]-R[i,j]*x[j]
        x[i]=x[i]/R[i,i]
    return x
R=np.triu(np.random.random((4,4)))
b=np.random.random(4)
x=back_subst(R,b)
np.linalg.norm(R@x-b) 

In [ ]:
#using QR factorization and back substitution to solve problem
def solve_via_backsub(A,b):
    Q,R=np.linalg.qr(A)
    b_tilde=Q.T@b
    x=back_subst(R,b_tilde)
    return x

In [2]:
#solve the linear equations and the time they need
# 1. np.linalg.solve(A,b)
# 2. x=np.linalg.inv(A)@b
import time
import numpy as np
n = 5000
A = np.random.normal(size = (n,n))
b = np.random.normal(size = n)
start = time.time()
x1 = np.linalg.solve(A,b)
end = time.time()
print(np.linalg.norm(b - A @ x1))
print(end - start)

start = time.time()
x2 = np.linalg.inv(A) @ b
end = time.time()
print(np.linalg.norm(b - A @ x2))
print(end - start)

2.6183431604924317e-09
2.1208295822143555
1.9651334264532704e-09
5.705203056335449


In [3]:
#pseudo-inverse
A = np.array([[-3,-4],[4,6],[1,1]])
np.linalg.pinv(A)

array([[-1.22222222, -1.11111111,  1.77777778],
       [ 0.77777778,  0.88888889, -1.22222222]])

In [4]:
A = np.array([[-3,-4],[4,6],[1,1]])
Q,R=np.linalg.qr(A)
np.linalg.inv(R)@Q.T
#np.linalg.solve(R,Q.T)

array([[-1.22222222, -1.11111111,  1.77777778],
       [ 0.77777778,  0.88888889, -1.22222222]])