In [2]:
import numpy as np
a=np.array([[0,1,-2.3,0.1],[1.3,4,-0.1,1],[4.1,-1,0,1.7]])
a.shape

(3, 4)

In [3]:
m,n=a.shape
print('m:',m)
print('n:',n)

m: 3
n: 4


In [5]:
tall=lambda x: a.shape[0]>a.shape[1]
tall(a)

False

In [3]:
import numpy as np
a=np.array([[0,1,-2.3,0.1],[1.3,4,-0.1,1],[4.1,-1,0,1.7]])
print('m:',len(a))
print('n:',len(a[0]))
a[0,2]

m: 3
n: 4


-2.3

In [4]:
a=np.array([[0,1,-2.3,0.1],[1.3,4,-0.1,1],[4.1,-1,0,1.7]])
a[0,2]=7.5
a

array([[ 0. ,  1. ,  7.5,  0.1],
       [ 1.3,  4. , -0.1,  1. ],
       [ 4.1, -1. ,  0. ,  1.7]])

In [6]:
b=a.copy()
a==b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
b[0,3]=100
np.sum(a==b)

11

In [9]:
a=[[0,1,-2.3,0.1],[1.3,4,-0.1,1],[4.1,-1,0,1.7]]
b=[[1,1,-2.3,0.1],[1.3,4,-0.1,1],[4.1,-1,0,1.7]]
a==b

False

In [15]:
# a 3 vector
a=np.array([-2.1,-3,0])
a.shape

(1, 3)

In [19]:
# a 3-vector or a 3 by 1 matrix
b=np.array([[-2.1],[-3],[0]])
b.shape

(3, 1)

In [20]:
b.reshape(3)

array([-2.1, -3. ,  0. ])

In [17]:
# a 3-row vector or a 1 by 3 matrix
c=np.array([[-2.1,-3,0]])
c.shape

(1, 3)

In [21]:
a=np.array([[-1,0,2,1],[2,-3,0,1],[0,4,2,1]])
a[0:2,2:4]

array([[2, 1],
       [0, 1]])

In [22]:
#third col of A
a[:,2]

array([2, 0, 2])

In [23]:
#second row of A, returned as vector
a[1,:]

array([ 2, -3,  0,  1])

In [24]:
a.reshape(6,2)

array([[-1,  0],
       [ 2,  1],
       [ 2, -3],
       [ 0,  1],
       [ 0,  4],
       [ 2,  1]])

In [25]:
a.reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [32]:
b=np.array([1,2,3])
c=np.array([-1])
d=np.array([[2,2,1],[3,1,4]])
e=np.array([[4],[4]])
#construct 3 by 4 block matrix
a=np.block([[b,c],[d,e]])
a

array([[ 1,  2,  3, -1],
       [ 2,  2,  1,  4],
       [ 3,  1,  4,  4]])

In [33]:
a=[1,2]
b=[4,5]
c=[2,5]
A=np.vstack([a,b,c])
B=np.hstack([a,b,c])
print('matrix A :',A)
print('dimension of A:',A.shape)
print('matrix B :',B)
print('dimension of B:',B.shape)

matrix A : [[1 2]
 [4 5]
 [2 5]]
dimension of A: (3, 2)
matrix B : [1 2 4 5 2 5]
dimension of B: (6,)


In [34]:
a=[[1],[2]]
b=[[2],[5]]
c=[[3],[6]]
A=np.vstack([a,b,c])
B=np.hstack([a,b,c])
print('matrix of A :',A)
print('dimension of A:',A.shape)
print('matrix of B :',B)
print('dimension of B:',B.shape)

matrix of A : [[1]
 [2]
 [2]
 [5]
 [3]
 [6]]
dimension of A: (6, 1)
matrix of B : [[1 2 3]
 [2 5 6]]
dimension of B: (2, 3)


In [36]:
np.c_[-np.identity(3),np.zeros(3)]

array([[-1., -0., -0.,  0.],
       [-0., -1., -0.,  0.],
       [-0., -0., -1.,  0.]])

In [38]:
np.r_[-np.identity(3),np.zeros((1,3))]

array([[-1., -0., -0.],
       [-0., -1., -0.],
       [-0., -0., -1.],
       [ 0.,  0.,  0.]])

In [39]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
x=np.array([[0,1,2],[2,4,5],[6,1,7]])
print(np.diag(x))

[0 4 7]


In [43]:
print(np.diag(np.diag(x)))

[[0 0 0]
 [0 4 0]
 [0 0 7]]


In [44]:
np.random.random((2,3))

array([[0.02830087, 0.56263376, 0.27324583],
       [0.35393952, 0.8559847 , 0.23052706]])

In [45]:
np.random.randn(3,2)

array([[-0.52655408,  0.38317235],
       [ 1.49480414, -0.45267029],
       [ 1.59582019,  0.62609543]])

In [47]:
from scipy import sparse
i=np.array([0,1,1,0,2,3]) # row indexes of nonzeros
j=np.array([0,0,1,2,2,3]) # column indexes
v=np.array([-1.1,0.15,-0.1,1.17,-0.3,0.13]) # value
a=sparse.coo_matrix((v,(i,j)),shape=(4,5))
a

<4x5 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in COOrdinate format>

In [48]:
a.nnz

6

In [49]:
a.todense()

matrix([[-1.1 ,  0.  ,  1.17,  0.  ,  0.  ],
        [ 0.15, -0.1 ,  0.  ,  0.  ,  0.  ],
        [ 0.  ,  0.  , -0.3 ,  0.  ,  0.  ],
        [ 0.  ,  0.  ,  0.  ,  0.13,  0.  ]])

In [50]:
diagonals=[[1,2,3,4],[1,2,3],[1,2]]
b=sparse.diags(diagonals,offsets=[0,-1,2])
b.todense()

matrix([[1., 0., 1., 0.],
        [1., 2., 0., 2.],
        [0., 2., 3., 0.],
        [0., 0., 3., 4.]])

In [51]:
matrix=sparse.rand(3,4,density=0.25,format='csr',random_state=42)
matrix.todense()

matrix([[0.05641158, 0.        , 0.        , 0.65088847],
        [0.        , 0.        , 0.        , 0.14286682],
        [0.        , 0.        , 0.        , 0.        ]])

In [52]:
h=np.array([[0,1,-2,1],[2,-1,3,0]])
h.T

array([[ 0,  2],
       [ 1, -1],
       [-2,  3],
       [ 1,  0]])

In [53]:
np.transpose(h)

array([[ 0,  2],
       [ 1, -1],
       [-2,  3],
       [ 1,  0]])

In [54]:
u=np.array([[0,4],[7,0],[3,1]])
v=np.array([[1,2],[2,3],[0,4]])
u+v

array([[1, 6],
       [9, 3],
       [3, 5]])

In [55]:
2.2*u

array([[ 0. ,  8.8],
       [15.4,  0. ],
       [ 6.6,  2.2]])

In [56]:
a=np.array([[2,3,-1],[0,-1,4]])
np.linalg.norm(a)

5.5677643628300215

In [57]:
np.linalg.norm(a[:])

5.5677643628300215

In [58]:
#check triangle inequality
a=np.array([[-1,0],[2,2]])
b=np.array([[3,1],[-3,2]])
print(np.linalg.norm(a+b))
print(np.linalg.norm(a)+np.linalg.norm(b))

4.69041575982343
7.795831523312719


In [60]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
m,n=a.shape
print(a.shape)
sum_of_sq=0
for i in range(m):
    for j in range(n):
        sum_of_sq+=a[i,j]**2
matrix_norm=np.sqrt(sum_of_sq)
print(matrix_norm)
print(np.linalg.norm(a))

(4, 3)
25.495097567963924
25.495097567963924


In [62]:
a=np.array([[0,2,-1],[-2,1,1]])
x=np.array([2,1,-1])
a@x

array([ 3, -4])

In [63]:
np.matmul(a,x)

array([ 3, -4])

In [69]:
#difference matrix
diff_mat=lambda n:np.c_[-np.identity(n-1),np.zeros(n-1)]+np.c_[np.zeros(n-1),np.identity(n-1)]
d=diff_mat(4)
x=np.array([-1,0,2,1])
d@x

array([ 1.,  2., -1.])

In [70]:
#difference matrix 实现方法二
diff_mat=lambda n: sparse.hstack([-sparse.eye(n-1),sparse.coo_matrix((n-1,1))])+sparse.hstack([sparse.coo_matrix((n-1,1)),sparse.eye(n-1)])
d=diff_mat(4)
d@np.array([-1,0,2,1])

array([ 1.,  2., -1.])

In [71]:
def running_sum(n):
    import numpy as np
    s=np.zeros((n,n))
    for i in range(n):
        for j in range(i+1):
            s[i,j]=1
    return s
running_sum(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [72]:
running_sum(4)@np.array([-1,1,2,0])

array([-1.,  0.,  2.,  2.])

In [74]:
#np.tril函数实现difference matrix
np.tril(np.ones((4,4)))

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [76]:
def vandermonde(t,n):
    m=len(t)
    v=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            v[i,j]=t[i]**(j)
    return v
vandermonde(np.array([-1,0,0.5,1]),5)

array([[ 1.    , -1.    ,  1.    , -1.    ,  1.    ],
       [ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 1.    ,  0.5   ,  0.25  ,  0.125 ,  0.0625],
       [ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ]])

In [77]:
vandermonde=lambda t,n:np.column_stack([t**i for i in range(n)])#按列合并向量形成矩阵
vandermonde(np.array([-1,0,0.5,1]),5)

array([[ 1.    , -1.    ,  1.    , -1.    ,  1.    ],
       [ 1.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 1.    ,  0.5   ,  0.25  ,  0.125 ,  0.0625],
       [ 1.    ,  1.    ,  1.    ,  1.    ,  1.    ]])

In [80]:
#the complexity of matrix-vector multiplication
import time
a=np.random.random((1000,10000))
x=np.random.random(10000)
start=time.time()
y=a@x
end=time.time()
print(end-start)

0.0019207000732421875


In [81]:
import time
a=np.random.random((5000,20000))
x=np.random.random(20000)
start=time.time()
y=a@x
end=time.time()
print(end-start)

0.017946958541870117


In [95]:
#show the increase in efficiency obtained by sparse matrix computations is seen from matrix-vectors multiplications with the difference matrix
n=10**4
ds=sparse.hstack([-sparse.eye(n-1),sparse.coo_matrix((n-1,1))])+sparse.hstack([sparse.coo_matrix((n-1,1)),sparse.eye(n-1)])
d=np.column_stack([np.eye(n-1),np.zeros(n-1)])+np.column_stack([np.zeros(n-1),np.eye(n-1)])
x=np.random.normal(size=n)
import time 
start=time.time()
d@x
end=time.time()
print(end-start)
#print(ds) 与 print(ds.toarray()) 的表示方式不同，但表示的矩阵均为difference matrix

#np.eye():生成对角阵，对角线上元素为1，其余元素为0
#sparse.hstack:按列堆叠矩阵

0.02034139633178711


In [96]:
start=time.time()
ds@x
end=time.time()
print(end-start)

0.0015044212341308594
